# Generated by Django 5.1 on 2024-08-18 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='footballfieldimage',
            name='football_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_field.footballfield'),
        ),
    ]
