# Generated by Django 5.1 on 2024-08-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('football_field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='football_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_field.footballfield'),
        ),
    ]
